# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kevinmeinert/src/liquidfun/lf/freeglut/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kevinmeinert/src/liquidfun/lf/freeglut/config.h.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kevinmeinert/src/liquidfun/lf/freeglut/freeglut.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kevinmeinert/src/liquidfun/lf/freeglut/version.cmake_))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckFunctionExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckIncludeFileCXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckIncludeFiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckTypeSize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindOpenGL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/FindX11.cmake))

/Users/kevinmeinert/src/liquidfun/lf/liquidfun/Box2D/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.10.1/bin/cmake -H/Users/kevinmeinert/src/liquidfun/lf/liquidfun/Box2D -B/Users/kevinmeinert/src/liquidfun/lf/liquidfun/Box2D
