
all:
	cd liquidfun/Box2D; cmake -G "Xcode"; open Box2D.xcodeproj
	@echo "in xcode, build TestBed for My Mac 64bit"

clean:
	rm -rf */CMakeFiles; rm -rf */CMakeCache.txt; rm -rf */cmake_install.cmake;
	rm -rf liquidfun/Box2D/CMakeFiles; rm -rf liquidfun/Box2D/CMakeCache.txt; rm -rf liquidfun/Box2D/cmake_install.cmake;  rm -rf liquidfun/Box2D/Box2D.build; rm -rf liquidfun/Box2D/Box2D.xcodeproj


